### ISSUE TITLE
Internal server error (502 Bad Gateway Error)

### ISSUE THREAD

**Issue by jazzlexter** [simalexan/api-lambda-send-email-ses#1]
I tried to test this stack out with PostMan, but this error is thrown whenever I send a POST to the endpoint.

![image](https://user-images.githubusercontent.com/31465922/50275097-9e021000-0479-11e9-9547-f8506929620d.png)

Here is my request :

```
POST /Prod/send HTTP/1.1
Host: as0s7czmo4.execute-api.ap-southeast-1.amazonaws.com
cache-control: no-cache
Postman-Token: 2add082b-b9b0-44fd-a8ff-4a135c56579d
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="toEmails"

foobar@email.com

Content-Disposition: form-data; name="subject"

[ Test Subject ]

Content-Disposition: form-data; name="message"

This is a test message
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by simalexan** [comment]
Hi @jazzlexter 

Sorry that you're having an issue. Can you try sending the `toEmails` as an Array of strings (emails)?
It says in the README that 
>The `toEmails`,`ccEmails`, and `replyToEmails` parameters must be of Array type.

But it's probably my mistake as it's not obvious enough. Will update the README both here and on the Serverless Application Repository. Thank you for pointing this out and thank you for using the component!

**Comment by simalexan** [comment]
@jazzlexter I've updated the README files both here and on the Serverless Application Repository.

**Comment by simalexan** [comment]
I'm going to be closing this issue now, if you experience the same problem again with this component, feel free to reopen it.

**Comment by jazzlexter** [comment]
@simalexan That solved the issue! Thanks for the quick response!

Also on another note.
Is there a way to like set which region the SES sends from?
Or is it automatically set?
'Cause right now it automatically sets it to where my Lambda is created

Thanks again, and great component!
