### ISSUE TITLE
Email sent directly in spam

### ISSUE THREAD

**Issue by JohanRin** [simalexan/api-lambda-send-email-ses#2]
Hi @simalexan,

When I send an email with your serverless application, the email go directly in the spam folder of my inbox.

The domain and email address are verified and the DKIM activated.
Is there something else to do to send an email "verified"?

**Comment by JohanRin** [comment]
I forgot to configure the **MAIL FROM Domain** and my test email was considered as spam because it was not long enough..

**Comment by simalexan** [comment]
@JohanRin sorry for the delay and im glad you got it resolved! I'm traveling at the moment, so im a bit sluggish in responses. Feel free to ask if you have any further issues!
